name: Deploy React App in Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repo
      uses: actions/checkout@v3

    - name: 🧱 Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: 📦 Install dependencies
      run: npm install

    - name: ✅ run unit test
      run: npm run test

    - name: 📈Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
       token: 2d3673af-c957-400a-b39d-a771beb33857

    - name: 🛠️ Build React app
      run: npm run build

    - name: 🐳 Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 🔐 Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: marylynvw
        password: dckr_pat_2uAy4FVwVHN9wpZlU9sVGsOSCgA 

    - name: 🏗️ Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfiles/Dockerfile
        push: true
        tags: marylynvw/app-ci-cd:latest
